### ISSUE TITLE
PHP 7....

### ISSUE THREAD

**Issue by svfolderOld** [thtmorais/yii2-dropdown#1]
Hello, your extension does not work on PHP 7.0, is this how it is intended?

**Comment by thtmorais** [comment]
Was there an error? If so, can you inform which one?

**Comment by svfolderOld** [comment]
Reale?
OMG...

ParseError
syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)

public string $dropdownToggleClass = 'btn btn-success';

**Comment by svfolderOld** [comment]
We use PHP 8 construction in extension...

**Comment by thtmorais** [comment]
Try new [version](https://github.com/thtmorais/yii2-dropdown/releases/tag/0.0.2).
